cmake_minimum_required(VERSION 3.22)
project(Gearsin LANGUAGES CXX)
option(ROGUE_BUILD_TESTS "Build Gearsin tests" ON)
add_subdirectory(engine/core)
add_subdirectory(engine/rendering)
add_subdirectory(engine/scene)
add_subdirectory(engine/mesh)
add_subdirectory(engine/materials)
add_subdirectory(engine/importer)
add_subdirectory(engine/assets)
add_subdirectory(engine/exporter)
if(ROGUE_BUILD_TESTS)
 enable_testing()
 add_subdirectory(tests/core)
 add_subdirectory(tests/rendering)
 add_subdirectory(tests/scene)
 add_subdirectory(tests/mesh)
 add_subdirectory(tests/materials)
 add_subdirectory(tests/importer)
 add_subdirectory(tests/exporter)
 add_subdirectory(tests/assets)
endif()
