#include "rogue/rendering/vulkan/vulkan_swapchain.hpp"
#if defined(ROGUE_ENABLE_VULKAN)
#include <algorithm>
namespace rogue::rendering::vulkan {
VulkanSwapchain::~VulkanSwapchain(){destroy();}
VkSurfaceFormatKHR VulkanSwapchain::choose_format(const std::vector<VkSurfaceFormatKHR>& f)const{for(auto x:f)if(x.format==VK_FORMAT_B8G8R8A8_UNORM&&x.colorSpace==VK_COLOR_SPACE_SRGB_NONLINEAR_KHR)return x;return f.front();}
VkPresentModeKHR VulkanSwapchain::choose_present_mode(const std::vector<VkPresentModeKHR>& m)const{if(!config_.vsync)for(auto x:m)if(x==VK_PRESENT_MODE_MAILBOX_KHR)return x;return VK_PRESENT_MODE_FIFO_KHR;}
VkExtent2D VulkanSwapchain::choose_extent(const VkSurfaceCapabilitiesKHR& c)const{if(c.currentExtent.width!=0xFFFFFFFFu)return c.currentExtent;VkExtent2D e{config_.width,config_.height};e.width=std::clamp(e.width,c.minImageExtent.width,c.maxImageExtent.width);e.height=std::clamp(e.height,c.minImageExtent.height,c.maxImageExtent.height);return e;}
bool VulkanSwapchain::initialize(VkPhysicalDevice p,VkDevice d,VkSurfaceKHR s,VkQueue q,std::uint32_t qf,const SwapchainConfig& c){destroy();if(!p||!d||!s||!q)return false;physical_device_=p;device_=d;surface_=s;queue_=q;queue_family_=qf;config_=c;return create();}
bool VulkanSwapchain::create(){std::uint32_t n=0;if(vkGetPhysicalDeviceSurfaceFormatsKHR(physical_device_,surface_,&n,nullptr)!=VK_SUCCESS||!n)return false;std::vector<VkSurfaceFormatKHR> formats(n);vkGetPhysicalDeviceSurfaceFormatsKHR(physical_device_,surface_,&n,formats.data());n=0;if(vkGetPhysicalDeviceSurfacePresentModesKHR(physical_device_,surface_,&n,nullptr)!=VK_SUCCESS||!n)return false;std::vector<VkPresentModeKHR> modes(n);vkGetPhysicalDeviceSurfacePresentModesKHR(physical_device_,surface_,&n,modes.data());VkSurfaceCapabilitiesKHR caps{};if(vkGetPhysicalDeviceSurfaceCapabilitiesKHR(physical_device_,surface_,&caps)!=VK_SUCCESS)return false;auto sf=choose_format(formats);format_=sf.format;color_space_=sf.colorSpace;extent_=choose_extent(caps);std::uint32_t count=caps.minImageCount+1;if(caps.maxImageCount&&count>caps.maxImageCount)count=caps.maxImageCount;VkSwapchainCreateInfoKHR i{VK_STRUCTURE_TYPE_SWAPCHAIN_CREATE_INFO_KHR};i.surface=surface_;i.minImageCount=count;i.imageFormat=format_;i.imageColorSpace=color_space_;i.imageExtent=extent_;i.imageArrayLayers=1;i.imageUsage=VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT;i.imageSharingMode=VK_SHARING_MODE_EXCLUSIVE;i.preTransform=caps.currentTransform;i.compositeAlpha=VK_COMPOSITE_ALPHA_OPAQUE_BIT_KHR;i.presentMode=choose_present_mode(modes);i.clipped=VK_TRUE;if(vkCreateSwapchainKHR(device_,&i,nullptr,&swapchain_)!=VK_SUCCESS)return false;std::uint32_t ic=0;vkGetSwapchainImagesKHR(device_,swapchain_,&ic,nullptr);images_.resize(ic);vkGetSwapchainImagesKHR(device_,swapchain_,&ic,images_.data());return create_views();}
bool VulkanSwapchain::create_views(){views_.clear();views_.reserve(images_.size());for(auto image:images_){VkImageViewCreateInfo v{VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO};v.image=image;v.viewType=VK_IMAGE_VIEW_TYPE_2D;v.format=format_;v.subresourceRange.aspectMask=VK_IMAGE_ASPECT_COLOR_BIT;v.subresourceRange.levelCount=1;v.subresourceRange.layerCount=1;VkImageView view{};if(vkCreateImageView(device_,&v,nullptr,&view)!=VK_SUCCESS)return false;views_.push_back(view);}return true;}
bool VulkanSwapchain::acquire(VkSemaphore available,VkFence fence,std::uint32_t& index){return vkAcquireNextImageKHR(device_,swapchain_,UINT64_MAX,available,fence,&index)==VK_SUCCESS;}
VkResult VulkanSwapchain::present(std::uint32_t index,VkSemaphore finished){VkPresentInfoKHR p{VK_STRUCTURE_TYPE_PRESENT_INFO_KHR};p.waitSemaphoreCount=1;p.pWaitSemaphores=&finished;p.swapchainCount=1;p.pSwapchains=&swapchain_;p.pImageIndices=&index;return vkQueuePresentKHR(queue_,&p);}
bool VulkanSwapchain::recreate(std::uint32_t w,std::uint32_t h){config_.width=w;config_.height=h;vkDeviceWaitIdle(device_);destroy();return create();}
void VulkanSwapchain::destroy()noexcept{if(device_){for(auto v:views_)vkDestroyImageView(device_,v,nullptr);if(swapchain_)vkDestroySwapchainKHR(device_,swapchain_,nullptr);}views_.clear();images_.clear();swapchain_=VK_NULL_HANDLE;}
}
#endif