#include "rogue/rendering/vulkan/vulkan_frame.hpp"
#if defined(ROGUE_ENABLE_VULKAN)
namespace rogue::rendering::vulkan {
VulkanFrameSync::~VulkanFrameSync(){destroy();}
bool VulkanFrameSync::initialize(VkDevice d,VkCommandPool p){destroy();if(!d||!p)return false;device_=d;pool_=p;VkSemaphoreCreateInfo s{VK_STRUCTURE_TYPE_SEMAPHORE_CREATE_INFO};if(vkCreateSemaphore(d,&s,nullptr,&image_available_)!=VK_SUCCESS)return false;if(vkCreateSemaphore(d,&s,nullptr,&render_finished_)!=VK_SUCCESS)return false;VkFenceCreateInfo f{VK_STRUCTURE_TYPE_FENCE_CREATE_INFO};f.flags=VK_FENCE_CREATE_SIGNALED_BIT;if(vkCreateFence(d,&f,nullptr,&fence_)!=VK_SUCCESS)return false;VkCommandBufferAllocateInfo a{VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO};a.commandPool=p;a.level=VK_COMMAND_BUFFER_LEVEL_PRIMARY;a.commandBufferCount=1;if(vkAllocateCommandBuffers(d,&a,&command_buffer_)!=VK_SUCCESS)return false;return true;}
bool VulkanFrameSync::wait()const{return fence_&&vkWaitForFences(device_,1,&fence_,VK_TRUE,UINT64_MAX)==VK_SUCCESS;}
bool VulkanFrameSync::begin(){if(!command_buffer_||recording_)return false;if(vkResetCommandBuffer(command_buffer_,0)!=VK_SUCCESS)return false;VkCommandBufferBeginInfo b{VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO};b.flags=VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT;recording_=vkBeginCommandBuffer(command_buffer_,&b)==VK_SUCCESS;return recording_;}
bool VulkanFrameSync::end(){if(!recording_)return false;recording_=false;return vkEndCommandBuffer(command_buffer_)==VK_SUCCESS;}
bool VulkanFrameSync::submit(VkQueue q,VkSemaphore available,VkSemaphore finished){if(!q||!command_buffer_||!available||!finished||!fence_||recording_)return false;VkPipelineStageFlags stage=VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT;VkSubmitInfo s{VK_STRUCTURE_TYPE_SUBMIT_INFO};s.waitSemaphoreCount=1;s.pWaitSemaphores=&available;s.pWaitDstStageMask=&stage;s.commandBufferCount=1;s.pCommandBuffers=&command_buffer_;s.signalSemaphoreCount=1;s.pSignalSemaphores=&finished;if(vkResetFences(device_,1,&fence_)!=VK_SUCCESS)return false;return vkQueueSubmit(q,1,&s,fence_)==VK_SUCCESS;}
void VulkanFrameSync::destroy()noexcept{if(device_){if(fence_)vkDestroyFence(device_,fence_,nullptr);if(render_finished_)vkDestroySemaphore(device_,render_finished_,nullptr);if(image_available_)vkDestroySemaphore(device_,image_available_,nullptr);if(command_buffer_&&pool_)vkFreeCommandBuffers(device_,pool_,1,&command_buffer_);}fence_=VK_NULL_HANDLE;render_finished_=VK_NULL_HANDLE;image_available_=VK_NULL_HANDLE;command_buffer_=VK_NULL_HANDLE;device_=VK_NULL_HANDLE;pool_=VK_NULL_HANDLE;recording_=false;}
}
#endif