#include "rogue/rendering/vulkan/vulkan_runtime.hpp"
#if defined(ROGUE_ENABLE_VULKAN)
#include <limits>
namespace rogue::rendering::vulkan {
VulkanRuntime::~VulkanRuntime(){destroy();}
std::uint32_t VulkanRuntime::memory_type(std::uint32_t bits,VkMemoryPropertyFlags p)const noexcept{VkPhysicalDeviceMemoryProperties m{};vkGetPhysicalDeviceMemoryProperties(physical_device_,&m);for(std::uint32_t i=0;i<m.memoryTypeCount;++i)if((bits&(1u<<i))&&(m.memoryTypes[i].propertyFlags&p)==p)return i;return std::numeric_limits<std::uint32_t>::max();}
bool VulkanRuntime::initialize(VkPhysicalDevice pd,VkDevice d,VkSurfaceKHR s,VkQueue q,std::uint32_t qf,VkFormat format,const std::vector<VkImageView>& views,std::uint32_t w,std::uint32_t h){destroy();if(!pd||!d||!q||!s||views.empty())return false;physical_device_=pd;device_=d;surface_=s;queue_=q;queue_family_=qf;color_format_=format;color_views_=views;extent_={w?w:1,h?h:1};return find_depth_format()&&create_depth_target()&&create_render_pass()&&create_framebuffers();}
bool VulkanRuntime::find_depth_format(){VkFormat candidates[]={VK_FORMAT_D32_SFLOAT,VK_FORMAT_D24_UNORM_S8_UINT,VK_FORMAT_D16_UNORM};for(auto f:candidates){VkFormatProperties p{};vkGetPhysicalDeviceFormatProperties(physical_device_,f,&p);if(p.optimalTilingFeatures&VK_FORMAT_FEATURE_DEPTH_STENCIL_ATTACHMENT_BIT){depth_format_=f;return true;}}return false;}
bool VulkanRuntime::create_depth_target(){VkImageCreateInfo i{VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO};i.imageType=VK_IMAGE_TYPE_2D;i.format=depth_format_;i.extent={extent_.width,extent_.height,1};i.mipLevels=1;i.arrayLayers=1;i.samples=VK_SAMPLE_COUNT_1_BIT;i.tiling=VK_IMAGE_TILING_OPTIMAL;i.usage=VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT;i.initialLayout=VK_IMAGE_LAYOUT_UNDEFINED;if(vkCreateImage(device_,&i,nullptr,&depth_image_)!=VK_SUCCESS)return false;VkMemoryRequirements r{};vkGetImageMemoryRequirements(device_,depth_image_,&r);auto mt=memory_type(r.memoryTypeBits,VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);if(mt==std::numeric_limits<std::uint32_t>::max())return false;VkMemoryAllocateInfo a{VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO};a.allocationSize=r.size;a.memoryTypeIndex=mt;if(vkAllocateMemory(device_,&a,nullptr,&depth_memory_)!=VK_SUCCESS)return false;if(vkBindImageMemory(device_,depth_image_,depth_memory_,0)!=VK_SUCCESS)return false;VkImageViewCreateInfo v{VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO};v.image=depth_image_;v.viewType=VK_IMAGE_VIEW_TYPE_2D;v.format=depth_format_;v.subresourceRange.aspectMask=VK_IMAGE_ASPECT_DEPTH_BIT;v.subresourceRange.levelCount=1;v.subresourceRange.layerCount=1;return vkCreateImageView(device_,&v,nullptr,&depth_view_)==VK_SUCCESS;}
bool VulkanRuntime::create_render_pass(){VkAttachmentDescription a[2]{};a[0].format=color_format_;a[0].samples=VK_SAMPLE_COUNT_1_BIT;a[0].loadOp=VK_ATTACHMENT_LOAD_OP_CLEAR;a[0].storeOp=VK_ATTACHMENT_STORE_OP_STORE;a[0].initialLayout=VK_IMAGE_LAYOUT_UNDEFINED;a[0].finalLayout=VK_IMAGE_LAYOUT_PRESENT_SRC_KHR;a[1].format=depth_format_;a[1].samples=VK_SAMPLE_COUNT_1_BIT;a[1].loadOp=VK_ATTACHMENT_LOAD_OP_CLEAR;a[1].storeOp=VK_ATTACHMENT_STORE_OP_DONT_CARE;a[1].initialLayout=VK_IMAGE_LAYOUT_UNDEFINED;a[1].finalLayout=VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL;VkAttachmentReference c{0,VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL};VkAttachmentReference d{1,VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL};VkSubpassDescription s{};s.pipelineBindPoint=VK_PIPELINE_BIND_POINT_GRAPHICS;s.colorAttachmentCount=1;s.pColorAttachments=&c;s.pDepthStencilAttachment=&d;VkSubpassDependency dep{};dep.srcSubpass=VK_SUBPASS_EXTERNAL;dep.dstSubpass=0;dep.srcStageMask=VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT;dep.dstStageMask=VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT;dep.dstAccessMask=VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT;VkRenderPassCreateInfo r{VK_STRUCTURE_TYPE_RENDER_PASS_CREATE_INFO};r.attachmentCount=2;r.pAttachments=a;r.subpassCount=1;r.pSubpasses=&s;r.dependencyCount=1;r.pDependencies=&dep;return vkCreateRenderPass(device_,&r,nullptr,&render_pass_)==VK_SUCCESS;}
bool VulkanRuntime::create_framebuffers(){framebuffers_.clear();for(auto view:color_views_){VkImageView views[2]={view,depth_view_};VkFramebufferCreateInfo f{VK_STRUCTURE_TYPE_FRAMEBUFFER_CREATE_INFO};f.renderPass=render_pass_;f.attachmentCount=2;f.pAttachments=views;f.width=extent_.width;f.height=extent_.height;f.layers=1;VkFramebuffer fb{};if(vkCreateFramebuffer(device_,&f,nullptr,&fb)!=VK_SUCCESS)return false;framebuffers_.push_back(fb);}return !framebuffers_.empty();}
bool VulkanRuntime::begin(VkCommandBuffer cmd,std::uint32_t image_index,VkClearColorValue color){if(!cmd||!render_pass_||image_index>=framebuffers_.size())return false;VkClearValue c[2]{};c[0].color=color;c[1].depthStencil={1.0f,0};VkRenderPassBeginInfo b{VK_STRUCTURE_TYPE_RENDER_PASS_BEGIN_INFO};b.renderPass=render_pass_;b.framebuffer=framebuffers_[image_index];b.renderArea.extent=extent_;b.clearValueCount=2;b.pClearValues=c;vkCmdBeginRenderPass(cmd,&b,VK_SUBPASS_CONTENTS_INLINE);VkViewport vp{0,0,float(extent_.width),float(extent_.height),0,1};VkRect2D sc{{0,0},extent_};vkCmdSetViewport(cmd,0,1,&vp);vkCmdSetScissor(cmd,0,1,&sc);return true;}
bool VulkanRuntime::end(VkCommandBuffer cmd){if(!cmd)return false;vkCmdEndRenderPass(cmd);return true;}
void VulkanRuntime::destroy()noexcept{if(device_){for(auto fb:framebuffers_)vkDestroyFramebuffer(device_,fb,nullptr);if(render_pass_)vkDestroyRenderPass(device_,render_pass_,nullptr);if(depth_view_)vkDestroyImageView(device_,depth_view_,nullptr);if(depth_image_)vkDestroyImage(device_,depth_image_,nullptr);if(depth_memory_)vkFreeMemory(device_,depth_memory_,nullptr);}framebuffers_.clear();color_views_.clear();render_pass_=VK_NULL_HANDLE;depth_view_=VK_NULL_HANDLE;depth_image_=VK_NULL_HANDLE;depth_memory_=VK_NULL_HANDLE;device_=VK_NULL_HANDLE;physical_device_=VK_NULL_HANDLE;surface_=VK_NULL_HANDLE;queue_=VK_NULL_HANDLE;extent_={1,1};}
}
#endif