#include "rogue/rendering/vulkan/vulkan_morph_buffer.hpp"
#include "rogue/rendering/vulkan/vulkan_buffer_copy.hpp"
#include "rogue/rendering/vulkan/vulkan_morph_packing.hpp"
#if defined(ROGUE_ENABLE_VULKAN)
#include <limits>
namespace rogue::rendering::vulkan {
VulkanMorphBuffer::~VulkanMorphBuffer(){destroy();}
std::uint32_t VulkanMorphBuffer::find_memory_type(std::uint32_t bits,VkMemoryPropertyFlags props)const noexcept{VkPhysicalDeviceMemoryProperties mp{};vkGetPhysicalDeviceMemoryProperties(physical_device_,&mp);for(std::uint32_t i=0;i<mp.memoryTypeCount;++i)if((bits&(1u<<i))&&(mp.memoryTypes[i].propertyFlags&props)==props)return i;return std::numeric_limits<std::uint32_t>::max();}
bool VulkanMorphBuffer::create_buffer(VkDeviceSize size){if(!size)return false;VkBufferCreateInfo bi{VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO};bi.size=size;bi.usage=VK_BUFFER_USAGE_STORAGE_BUFFER_BIT|VK_BUFFER_USAGE_TRANSFER_DST_BIT;bi.sharingMode=VK_SHARING_MODE_EXCLUSIVE;if(vkCreateBuffer(device_,&bi,nullptr,&buffer_)!=VK_SUCCESS)return false;VkMemoryRequirements r{};vkGetBufferMemoryRequirements(device_,buffer_,&r);auto mt=find_memory_type(r.memoryTypeBits,VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT);if(mt==std::numeric_limits<std::uint32_t>::max()){destroy();return false;}VkMemoryAllocateInfo ai{VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO};ai.allocationSize=r.size;ai.memoryTypeIndex=mt;if(vkAllocateMemory(device_,&ai,nullptr,&memory_)!=VK_SUCCESS){destroy();return false;}if(vkBindBufferMemory(device_,buffer_,memory_,0)!=VK_SUCCESS){destroy();return false;}size_=size;return true;}
bool VulkanMorphBuffer::initialize(VkPhysicalDevice pd,VkDevice d,VkQueue q,std::uint32_t qf,const MorphBuffer& source){destroy();if(!pd||!d||!q||source.packed_data().empty())return false;physical_device_=pd;device_=d;transfer_queue_=q;transfer_queue_family_=qf;PackedGpuMorphData packed;if(!pack_morph_buffer_for_gpu(source,packed)||packed.bytes.empty()||!create_buffer(packed.bytes.size())){destroy();return false;}if(!staging_.initialize(pd,d,packed.bytes.size(),VK_BUFFER_USAGE_STORAGE_BUFFER_BIT)){destroy();return false;}slices_.clear();slices_.reserve(source.slices().size());for(std::size_t i=0;i<source.slices().size();++i){const auto&s=source.slices()[i];slices_.push_back({s.morph_id,packed.offsets[i],s.element_count,(std::uint32_t)s.storage,(std::uint32_t)s.precision});}active_.clear();active_.reserve(source.active_morphs().size());for(const auto&a:source.active_morphs())active_.push_back({a.morph_id,a.weight});return true;}
bool VulkanMorphBuffer::update(VkCommandBuffer cmd,const MorphBuffer& source){if(!is_initialized()||!cmd)return false;PackedGpuMorphData packed;if(!pack_morph_buffer_for_gpu(source,packed)||packed.bytes.empty()||packed.bytes.size()>size_||packed.bytes.size()>staging_.size())return false;if(!staging_.upload(packed.bytes.data(),packed.bytes.size())||!record_buffer_copy_and_barrier(cmd,staging_.buffer(),buffer_,packed.bytes.size()))return false;slices_.clear();slices_.reserve(source.slices().size());for(std::size_t i=0;i<source.slices().size();++i){const auto&s=source.slices()[i];slices_.push_back({s.morph_id,packed.offsets[i],s.element_count,(std::uint32_t)s.storage,(std::uint32_t)s.precision});}active_.clear();active_.reserve(source.active_morphs().size());for(const auto&a:source.active_morphs())active_.push_back({a.morph_id,a.weight});return true;}
void VulkanMorphBuffer::destroy()noexcept{staging_.destroy();if(device_){if(buffer_)vkDestroyBuffer(device_,buffer_,nullptr);if(memory_)vkFreeMemory(device_,memory_,nullptr);}buffer_=VK_NULL_HANDLE;memory_=VK_NULL_HANDLE;size_=0;slices_.clear();active_.clear();device_=VK_NULL_HANDLE;physical_device_=VK_NULL_HANDLE;transfer_queue_=VK_NULL_HANDLE;transfer_queue_family_=0;}
}
#endif